# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Default

steps:
- script: echo My first maven azure
  displayName: 'Ruuning one-line Command'
- script: mvn clean install
  displayName: 'Building the project'
- script: java -jar target/Maven_App-1.0-SNAPSHOT.jar
  displayName: 'Running the Application'
